module.exports = Object.freeze({
    
     ROLE_TYPE_KEY: 'role_key',
     SUPER_ADMIN_ROLE: 'SUPER_ADMIN',
     ADMIN_ROLE: 'BDO',
     OPERATOR_ROLE: 'DEALING_OFFICER',
     CREATOR_ROLE: 'CC_OFFICER',

     NEW_STATE: 'NEW',
     ASSIGNED_STATE: 'ASSIGNED',
     IN_PROGRESS_STATE: 'IN-PROGRESS',
     RESOLVED_STATE: 'RESOLVED',
     CLOSED_STATE: 'CLOSED',
     CONCLUDED_STATE: 'CONCLUDED',
     DUMPPED_STATE: 'DUMPPED',

     TICKET_PRIORITY_HIGH: 'high',
     TICKET_PRIORITY_MED: 'med',
     TICKET_PRIORITY_LOW: 'low',
});